# automatically generated by the FlatBuffers compiler, do not modify

# namespace: stellarflow

class Flags(object):
    NONE = 0
    LIVE = 1
    STALE = 2
    ANOMALY = 4
    SYNTHETIC = 8
    HALTED = 16
