# automatically generated by the FlatBuffers compiler, do not modify

# namespace: stellarflow

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TelemetryBundle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TelemetryBundle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTelemetryBundle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TelemetryBundle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TelemetryBundle
    def Frames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from src.serialization.stellarflow.TelemetryFrame import TelemetryFrame
            obj = TelemetryFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TelemetryBundle
    def FramesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TelemetryBundle
    def FramesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TelemetryBundleStart(builder):
    builder.StartObject(1)

def Start(builder):
    TelemetryBundleStart(builder)

def TelemetryBundleAddFrames(builder, frames):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(frames), 0)

def AddFrames(builder, frames):
    TelemetryBundleAddFrames(builder, frames)

def TelemetryBundleStartFramesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFramesVector(builder, numElems):
    return TelemetryBundleStartFramesVector(builder, numElems)

def TelemetryBundleEnd(builder):
    return builder.EndObject()

def End(builder):
    return TelemetryBundleEnd(builder)
