# automatically generated by the FlatBuffers compiler, do not modify

# namespace: stellarflow

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TelemetryFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TelemetryFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTelemetryFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TelemetryFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TelemetryFrame
    def AssetId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # TelemetryFrame
    def AssetIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # TelemetryFrame
    def AssetIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TelemetryFrame
    def AssetIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # TelemetryFrame
    def Price(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TelemetryFrame
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TelemetryFrame
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TelemetryFrame
    def Sequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TelemetryFrame
    def Flags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TelemetryFrame
    def FeedId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def TelemetryFrameStart(builder):
    builder.StartObject(7)

def Start(builder):
    TelemetryFrameStart(builder)

def TelemetryFrameAddAssetId(builder, assetId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(assetId), 0)

def AddAssetId(builder, assetId):
    TelemetryFrameAddAssetId(builder, assetId)

def TelemetryFrameStartAssetIdVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartAssetIdVector(builder, numElems):
    return TelemetryFrameStartAssetIdVector(builder, numElems)

def TelemetryFrameAddPrice(builder, price):
    builder.PrependInt64Slot(1, price, 0)

def AddPrice(builder, price):
    TelemetryFrameAddPrice(builder, price)

def TelemetryFrameAddVolume(builder, volume):
    builder.PrependUint64Slot(2, volume, 0)

def AddVolume(builder, volume):
    TelemetryFrameAddVolume(builder, volume)

def TelemetryFrameAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(3, timestamp, 0)

def AddTimestamp(builder, timestamp):
    TelemetryFrameAddTimestamp(builder, timestamp)

def TelemetryFrameAddSequence(builder, sequence):
    builder.PrependUint32Slot(4, sequence, 0)

def AddSequence(builder, sequence):
    TelemetryFrameAddSequence(builder, sequence)

def TelemetryFrameAddFlags(builder, flags):
    builder.PrependUint16Slot(5, flags, 0)

def AddFlags(builder, flags):
    TelemetryFrameAddFlags(builder, flags)

def TelemetryFrameAddFeedId(builder, feedId):
    builder.PrependUint8Slot(6, feedId, 0)

def AddFeedId(builder, feedId):
    TelemetryFrameAddFeedId(builder, feedId)

def TelemetryFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return TelemetryFrameEnd(builder)
